optimized website load time
ANSHIKA-26/WordWise pull request #1618
Opened 2024-11-02 10:59 UTC by shivam8112005

### Pull Request Checklist
Fixes #1605 

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

https://github.com/user-attachments/assets/7822d2c3-44e1-4cf3-8a3b-393e3b55dedc

2024-11-02 11:00 UTC, shivam8112005 commented
@ANSHIKA-26  is it possible to add level 2 ?

2024-11-02 14:10 UTC, ANSHIKA-26 requested changes

2024-11-02 14:10 UTC, ANSHIKA-26 commented on style.css
> -/* --light: #f0e4d7;
add this back , it might be needed for refrence in future

2024-11-02 14:11 UTC, ANSHIKA-26 commented
> @ANSHIKA-26 close #1378 and is it possible to add level 2 ?

sorry , cant give a level 2 for removing comments and doing some minor fixes

2024-11-02 14:15 UTC, shivam8112005 commented
ohk np wait

2024-11-02 14:20 UTC, shivam8112005 commented
is it ok now?

2024-11-02 19:15 UTC, shivam8112005 commented
@ANSHIKA-26  can you please merge it now?

2024-11-03 09:19 UTC, hiteashgupta1 commented
Refork and resync

2024-11-03 09:31 UTC, shivam8112005 commented
It means delete this repo from my acc and then refork it again?

2024-11-03 09:33 UTC, closed without merging