Done Changing the profile icon
ANSHIKA-26/WordWise pull request #1647
Opened 2024-11-03 13:42 UTC by Ashmitha2606

### Pull Request Checklist

- [ ] I have added screenshots and videos to show before and after the working of my code.
- [ ] I have ensured that the screen size is set to 100% while making the video.
- [ ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [ ] I understand that if any the above conditions are not met , my PR will not be MERGED .

2024-11-03 14:35 UTC, ANSHIKA-26 commented
its not working , on clicking it nothing happens , kindly fix

2024-11-03 14:37 UTC, ANSHIKA-26 requested changes

2024-11-03 14:37 UTC, ANSHIKA-26 commented on index.html
> +                    <a href="#" class="profile-icon" id="profileDropdown" onclick="toggleDropdown()">
keep the anchor tag , just change the style , if you change the class and onClick event ,it will change the js code too

2024-11-03 15:08 UTC, Ashmitha2606 commented
@ANSHIKA-26 i have done the changes please see #1646

2024-11-03 15:13 UTC, Ashmitha2606 commented
@ANSHIKA-26 hey hi  #1644 i have changed this issue too can you award this one seperatelyy

2024-11-04 08:48 UTC, ANSHIKA-26 commented
can you please follow PR checklist and open a new PR ,? i need before and after changes pictures , a clear description of what you did and issue numbers , also you need to sync fork , thanks

2024-11-04 08:48 UTC, closed without merging

2024-11-04 10:18 UTC, Ashmitha2606 commented
Ok sure mill make a new pr and send